-- OCTAVA: AI avatars (generated by the generate-avatar Edge Function).
--
-- * profiles.avatar_path points into the private "avatars" bucket at
--   <profile_id>/<file>. Clients can read it but not set it; only the Edge
--   Function (service role) writes avatars and this column.
-- * avatar_generations logs each generation for the daily limit. Clients
--   can't touch it at all.
-- * get_deck also returns avatar_path.

alter table public.profiles
  add column avatar_path text check (avatar_path is null or avatar_path like id::text || '/%');
grant select (avatar_path) on public.profiles to authenticated;

create table public.avatar_generations (
  id bigint generated always as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now()
);
create index avatar_generations_profile_idx on public.avatar_generations (profile_id, created_at);
alter table public.avatar_generations enable row level security;
revoke all on public.avatar_generations from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', false, 5242880, array['image/jpeg', 'image/png', 'image/webp']);

-- private.clip_owner reads the owner id from the first folder of any object
-- path, so it works for avatars too.
create policy "See avatars in your age group"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'avatars'
    and (private.clip_owner(name) = (select auth.uid()) or private.same_age_group(private.clip_owner(name)))
  );

-- get_deck gains a column, which needs a drop and re-create.
drop function public.get_deck(double precision, text[], public.skill_level, text[], public.goal[], public.rehearsal_frequency[], int);

create function public.get_deck(
  max_km double precision default 25,
  instrument_ids text[] default null,
  min_skill public.skill_level default null,
  genre_filter text[] default null,
  goal_filter public.goal[] default null,
  frequency_filter public.rehearsal_frequency[] default null,
  max_results int default 20
)
returns table (
  id uuid,
  display_name text,
  age int,
  area text,
  distance_km int,
  looking_for text,
  genres text[],
  influences text[],
  goals public.goal[],
  rehearsal_frequency public.rehearsal_frequency,
  availability_note text,
  has_own_gear boolean,
  has_car boolean,
  has_rehearsal_space boolean,
  has_home_studio boolean,
  avatar_path text,
  instruments jsonb,
  links jsonb,
  clips jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  with me as (
    select p.id, p.lat, p.lng from public.profiles p where p.id = auth.uid()
  ),
  candidates as (
    select p.*,
      case when me.lat is not null and p.lat is not null
        then private.distance_km(me.lat, me.lng, p.lat, p.lng) end as km
    from public.profiles p, me
    where p.id <> me.id
      and private.same_age_group(p.id)
      and not private.is_blocked_between(me.id, p.id)
      and not exists (select 1 from public.swipes s where s.swiper_id = me.id and s.target_id = p.id)
      and (genre_filter is null or p.genres && (select array_agg(lower(g)) from unnest(genre_filter) g))
      and (goal_filter is null or p.goals && goal_filter)
      and (frequency_filter is null or p.rehearsal_frequency = any (frequency_filter))
      and (instrument_ids is null or exists (
        select 1 from public.profile_instruments pi
        where pi.profile_id = p.id
          and pi.instrument_id = any (instrument_ids)
          and (min_skill is null or pi.skill >= min_skill)
      ))
  )
  select
    c.id, c.display_name, private.age_of(c.id), c.area,
    case when c.km is not null then greatest(1, round(c.km))::int end,
    c.looking_for, c.genres, c.influences, c.goals, c.rehearsal_frequency,
    c.availability_note, c.has_own_gear, c.has_car, c.has_rehearsal_space, c.has_home_studio,
    c.avatar_path,
    coalesce((select jsonb_agg(jsonb_build_object('instrument', pi.instrument_id, 'skill', pi.skill, 'is_primary', pi.is_primary)
                               order by pi.is_primary desc, pi.instrument_id)
              from public.profile_instruments pi where pi.profile_id = c.id), '[]'::jsonb),
    coalesce((select jsonb_agg(jsonb_build_object('kind', l.kind, 'url', l.url))
              from public.profile_links l where l.profile_id = c.id), '[]'::jsonb),
    coalesce((select jsonb_agg(jsonb_build_object('id', a.id, 'path', a.storage_path, 'title', a.title, 'seconds', a.duration_seconds)
                               order by a.created_at)
              from public.audio_clips a where a.profile_id = c.id), '[]'::jsonb)
  from candidates c
  where max_km is null or c.km is null or c.km <= max_km
  order by c.km asc nulls last, c.created_at desc
  limit least(greatest(max_results, 1), 50);
$$;

revoke execute on function public.get_deck(double precision, text[], public.skill_level, text[], public.goal[], public.rehearsal_frequency[], int)
  from public, anon;
grant execute on function public.get_deck(double precision, text[], public.skill_level, text[], public.goal[], public.rehearsal_frequency[], int)
  to authenticated;
